// import styles from "./index.module.css";
import { type NextPage } from "next";
import Head from "next/head";
import AnotherChild from "../components/AnotherChild";
import Child from "../components/Child";

import React, { createContext, useState } from "react";

interface ThemeCtx {
  darkTheme: boolean;
  setDarkTheme: React.Dispatch<React.SetStateAction<boolean>>;
}

export const ThemeContext = createContext<ThemeCtx>({darkTheme:false, setDarkTheme:()=>null});


const Home: NextPage = () => {
  const [darkTheme, setDarkTheme] = useState(false);

  return (
    <>
      <Head>
        <title>Testing Context</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ThemeContext.Provider value={{ darkTheme, setDarkTheme }}>
          <AnotherChild/>
          <Child />

        </ThemeContext.Provider>
      </main>
    </>
  );
};

export default Home;
