// import styles from "./index.module.css";
import { type NextPage } from "next";
import Head from "next/head";
import AnotherChild from "../components/AnotherChild";
import Child from "../components/Child";

import React, { createContext, useState } from "react";

interface ThemeCtx {
  inputValue: string;
  setInputVal: React.Dispatch<React.SetStateAction<string>>;
}

export const ThemeContext = createContext<ThemeCtx>({inputValue:"value1", setInputVal:()=>null});


const Home: NextPage = () => {
  const [inputValue, setInputVal] = useState("value1");

  return (
    <>
      <Head>
        <title>Testing Context</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ThemeContext.Provider value={{ inputValue, setInputVal}}>
          <AnotherChild/>
          <Child />

        </ThemeContext.Provider>
      </main>
    </>
  );
};

export default Home;
